### ISSUE TITLE
Run multiple simultaneous tunnels that have stable public ports

### ISSUE THREAD

**Issue by elgalu** [defunctzombie/localtunnel-server#29]
If I need to expose a set of ports that need to work together, let's say ports 3000 and 4000 it would be nice to be able to configure it somehow, e.g.

```
tunnels:
  frontend:
    local_addr: localhost:3000
    remote_addr: elgalu.localtunnel.me:3000
  backend:
    local_addr: localhost:4000
    remote_addr: elgalu.localtunnel.me:4000
```

Also, would be any conflicts with fixed ports numbers? what if another user wants to use ports 3000 and 4000? even though it sets a different subdomain, if all resolve to the same IP and network interface there will be collisions right?
